name: Deploy to Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or your preferred Node.js version

    - name: Install dependencies
      run: yarn

    - name: Build project
      run: yarn build

    - name: Deploy to server
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        echo "$DEPLOY_SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" dist/ syukuba@syukuba.net:~/www/2024-test
        rm deploy_key.pem
